[package]
name = "kcp-bind"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
kcp = { git = "https://github.com/rupansh/kcp", rev = "bb5f54c722e5c342d4c17cb356125e5f429fe2bc" }
napi = { version = "2", default-features = false, features = ["napi4"] }
napi-derive = "2"

[build-dependencies]
napi-build = "1"